name: Check Package

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.1, 8.0, 7.4 ]
        stability: [ prefer-stable ]

    name: PHP${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap

      - name: Install package
        run: composer require phpjuice/opencf
